openapi: 3.0.3
info:
  title: Customer Service API
  version: 0.0.1
  contact:
    name: Suporte a API
    email: guilherme_gmc@outlook.com
    
servers:
  - url: http://localhost:8080/customer-service
    description: Servidor local de desenvolvimento
  - url: http://localhost:8080/customer-service
    description: Servidor cloud para testes

paths:
  /clientes:
    post:
      tags:
        - Clientes
      summary: Cadastrar um novo cliente
      operationId: criarCliente
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomerRegisterRequest'
      responses:
        '201':
          description: Cliente criado com sucesso
          headers:
            Location:
              description: URL do novo recurso
              schema:
                type: string
                example: /usuarios/550e8400-e29b-41d4-a716-446655440000
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerRegisterResponse'
        '400':
          description: Dados inválidos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerRegisterErrorResponse'
        '409':
          description: CPF ou e-mail já cadastrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerRegisterErrorResponse'
              example:
                detalhes:
                  - campo: "cpf"
                    situacao: "CPF já cadastrado."
                  - campo: "email"
                    situacao: "E-mail já cadastrado."
                mensagem: "DADOS_INVALIDOS"
        '500':
          description: Erro interno no servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /login:
    post:
      tags:
        - Autenticação
      summary: Realizar login do cliente
      operationId: autenticarCliente
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomerLoginRequest'
            examples:
              exemploLoginCpf:
                summary: Login com CPF
                value:
                  identificador: "12345678901"
                  senha: "Senha123@"
              exemploLoginEmail:
                summary: Login com e-mail
                value:
                  identificador: "joao@example.com"
                  senha: "Senha123@"
      responses:
        '200':
          description: Autenticação realizada com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerLoginResponse'
        '400':
          description: Requisição inválida (dados malformados)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerLoginErrorResponse'
        '401':
          description: Credenciais inválidas
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerLoginErrorResponse'
        '500':
          description: Erro interno no servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    CustomerRegisterRequest:
      type: object
      required:
        - cpf
        - email
        - nome
        - telefone
        - dataNascimento
        - genero
        - senha
      properties:
        cpf:
          type: string
          example: "12345678901"
          minLength: 11
          maxLength: 11
          pattern: '^[0-9]{11}$'
          description: CPF do cliente.
        email:
          type: string
          format: email
          example: "joao@example.com"
          minLength: 5
          maxLength: 200
          description: Email do cliente.
        nome:
          type: string
          example: "Guilherme Mendes"
          minLength: 5
          maxLength: 80
          description: Nome completo do cliente.
        telefone:
          type: string
          example: "11999998888"
          minLength: 11
          maxLength: 11
          pattern: '^[0-9]{10,11}$'
          description: Telefone celular com DDD do cliente.
        dataNascimento:
          type: string
          format: date
          example: "1990-01-01"
          description: Data de nascimento do cliente.
        genero:
          type: string
          enum: 
            - MASCULINO
            - FEMININO
            - OUTROS
            - NAO_INFORMAR
          description: Gênero do cliente.
        senha:
          type: string
          format: password
          minLength: 8
          maxLength: 20
          pattern: '^(?=.*[A-Z])(?=.*[a-z])(?=.*\\d)(?=.*[!@#$%^&*()_+]).{8,}$'
          example: "R8m!tQ2_pL9"
          description: Senha do cliente com obrigatóriedade de ter pelo menos 1 letra maiúscula, 1 minúscula, 1 dígito e 1 caractere especial do conjunto !@#$%^&*()_+ e restringe os caracteres aos permitidos (letras, dígitos e os especiais listados).
    
    CustomerRegisterResponse:
      type: object
      properties:
        detalhes:
          type: object
          properties:
            clienteId:
              type: string
              format: uuid
              example: "b19c1d76-02cc-4f7f-8233-928f2a3a55ff"
            dataCriacao:
              type: string
              format: date
        mensagem:
          type: string
          enum: 
            - CLIENTE_CADASTRADO_COM_SUCESSO
          
    CustomerRegisterErrorResponse:
      type: object
      properties:
        detalhes:
          type: array
          items:
            type: object
            properties:
              campo:
                type: string
                example: "cpf"
              situacao:
                type: string
                example: "CPF Invalido."
        mensagem:
          type: string
          enum: 
            - DADOS_INVALIDOS

    CustomerLoginRequest:
      type: object
      required:
        - identificador
        - senha
      properties:
        identificador:
          type: string
          example: "joao@example.com"
          description: "Pode ser o e-mail ou o CPF do usuário"
          minLength: 5
          maxLength: 200
        senha:
          type: string
          format: password
          example: "Senha123@"
          pattern: '^(?=.*[A-Z])(?=.*[a-z])(?=.*\\d)(?=.*[!@#$%^&*()_+]).{8,}$'
          minLength: 8
          maxLength: 20

    CustomerLoginResponse:
      type: object
      required:
        - token
        - tipoToken
        - expiracao
        - clientId
      properties:
        token:
          type: string
          description: Token JWT de autenticação
          example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
        tipoToken:
          type: string
          example: "Bearer"
        expiracao:
          type: string
          format: date-time
          example: "2025-10-15T20:00:00Z"
        clientId:
          type: string
          format: uuid
          example: "550e8400-e29b-41d4-a716-446655440000"

    CustomerLoginErrorResponse:
      type: object
      properties:
        mensagem:
          type: string
          enum:
            - CREDENCIAIS_INVALIDAS
            - DADOS_INVALIDOS
          example: "CREDENCIAIS_INVALIDAS"
        detalhes:
          type: array
          items:
            type: object
            properties:
              campo:
                type: string
                example: "identificador"
              situacao:
                type: string
                example: "CPF Inválido."
        
    ErrorResponse:
      type: object
      required:
        - timestamp
        - path
        - message
        - traceId
      properties:
        timestamp:
          type: string
          format: date-time
          example: "2025-10-15T19:35:42Z"
        error:
          type: string
          example: "Internal Server Error"
          description: Descrição resumida do erro
        message:
          type: string
          example: "Erro inesperado ao processar a solicitação."
          description: Mensagem de erro mais detalhada
        path:
          type: string
          example: "/usuarios"
          description: Caminho do endpoint em que ocorreu o erro
        traceId:
          type: string
          format: uuid
          example: "b5a8e2c8-3e54-4f73-a2b0-f9b1dbfa34cc"
          description: ID da requisição para rastreamento em logs e sistemas de monitoramento







